### ISSUE TITLE
integrate "dat publish"

### ISSUE THREAD

**Issue by yoshuawuyts** [dat-land/dat-desktop#332] opened 2017-04-20 01:19 UTC
As per our call last week: once the datproject.org api is ready, and we have login (#134)  we should integrate "dat publish" functionality

**Comment by yoshuawuyts** [comment] 2017-05-04 12:02
@karissa saw you removed the `Status: Blocked` label. Could you perhaps link to the API (source/docs) on how to create accounts and publish to datproject.org? Thanks!

**Comment by martinheidegger** [comment] 2018-11-09 05:47
Noting that #418 would take care of this.

**Comment by martinheidegger** [comment] 2018-11-09 06:00
Closing because it looks like a duplicate of #59 - please reopen if I am mistaken.

**Closed by martinheidegger** 2018-11-09 06:00 UTC
Labels: Priority: Medium, Status: Proposal, Type: Enhancement
