### ISSUE TITLE
Support Drag & Drop to app.

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/dat-desktop#496] opened 2018-02-02 06:10 UTC
Currently it seems only possible to drag & drop to the open app. It should be possible to do drag & drop to the application. _Creature comforts - tested on a mac_

**Comment by juliangruber** [comment] 2018-02-02 11:19
sorry I wasn't very clear here, dupe of https://github.com/dat-land/dat-desktop/issues/472

**Closed by juliangruber** 2018-02-02 11:19 UTC
